FROM golang:1.22.5 AS builder

WORKDIR /app

COPY services/core/go.mod services/core/go.sum ./
COPY pkg/ ../pkg/

RUN go mod download

COPY services/core/internal ./internal
COPY services/core/cmd ./cmd
COPY services/core/database/db.go ./database/db.go

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o api ./cmd/api/main.go

FROM alpine:latest AS runner

WORKDIR /root/

RUN apk update && apk add postgresql-client

COPY --from=builder /app/api ./api
COPY scripts/entrypoint.sh ./
COPY scripts/wait-to-db-ready.sh ./

RUN chmod +x ./entrypoint.sh
RUN chmod +x ./wait-to-db-ready.sh

CMD [ "sh", "entrypoint.sh" ]