// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	profile "github.com/modasby/futeboxd-backend/core/internal/profile"
	pagination "github.com/modasby/futeboxd-backend/core/pkg/pagination"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// FindOneByUsername mocks base method.
func (m *MockRepository) FindOneByUsername(ctx context.Context, username, requesterID string) (*profile.Profile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOneByUsername", ctx, username, requesterID)
	ret0, _ := ret[0].(*profile.Profile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOneByUsername indicates an expected call of FindOneByUsername.
func (mr *MockRepositoryMockRecorder) FindOneByUsername(ctx, username, requesterID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOneByUsername", reflect.TypeOf((*MockRepository)(nil).FindOneByUsername), ctx, username, requesterID)
}

// Follow mocks base method.
func (m *MockRepository) Follow(ctx context.Context, followerID, followingID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Follow", ctx, followerID, followingID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Follow indicates an expected call of Follow.
func (mr *MockRepositoryMockRecorder) Follow(ctx, followerID, followingID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Follow", reflect.TypeOf((*MockRepository)(nil).Follow), ctx, followerID, followingID)
}

// IsFollowing mocks base method.
func (m *MockRepository) IsFollowing(ctx context.Context, followerID, followingID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsFollowing", ctx, followerID, followingID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsFollowing indicates an expected call of IsFollowing.
func (mr *MockRepositoryMockRecorder) IsFollowing(ctx, followerID, followingID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsFollowing", reflect.TypeOf((*MockRepository)(nil).IsFollowing), ctx, followerID, followingID)
}

// ListFollowers mocks base method.
func (m *MockRepository) ListFollowers(ctx context.Context, requesterID, username string, page *pagination.Page) ([]profile.Profile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFollowers", ctx, requesterID, username, page)
	ret0, _ := ret[0].([]profile.Profile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFollowers indicates an expected call of ListFollowers.
func (mr *MockRepositoryMockRecorder) ListFollowers(ctx, requesterID, username, page interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFollowers", reflect.TypeOf((*MockRepository)(nil).ListFollowers), ctx, requesterID, username, page)
}

// ListFollowing mocks base method.
func (m *MockRepository) ListFollowing(ctx context.Context, requesterID, username string, page *pagination.Page) ([]profile.Profile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFollowing", ctx, requesterID, username, page)
	ret0, _ := ret[0].([]profile.Profile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFollowing indicates an expected call of ListFollowing.
func (mr *MockRepositoryMockRecorder) ListFollowing(ctx, requesterID, username, page interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFollowing", reflect.TypeOf((*MockRepository)(nil).ListFollowing), ctx, requesterID, username, page)
}

// ListPopularProfiles mocks base method.
func (m *MockRepository) ListPopularProfiles(ctx context.Context, requesterID string, page *pagination.Page) ([]profile.Profile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPopularProfiles", ctx, requesterID, page)
	ret0, _ := ret[0].([]profile.Profile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPopularProfiles indicates an expected call of ListPopularProfiles.
func (mr *MockRepositoryMockRecorder) ListPopularProfiles(ctx, requesterID, page interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPopularProfiles", reflect.TypeOf((*MockRepository)(nil).ListPopularProfiles), ctx, requesterID, page)
}

// Search mocks base method.
func (m *MockRepository) Search(ctx context.Context, requesterID, term string, page *pagination.Page) ([]profile.Profile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, requesterID, term, page)
	ret0, _ := ret[0].([]profile.Profile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockRepositoryMockRecorder) Search(ctx, requesterID, term, page interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockRepository)(nil).Search), ctx, requesterID, term, page)
}

// Unfollow mocks base method.
func (m *MockRepository) Unfollow(ctx context.Context, followerID, followingID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unfollow", ctx, followerID, followingID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Unfollow indicates an expected call of Unfollow.
func (mr *MockRepositoryMockRecorder) Unfollow(ctx, followerID, followingID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unfollow", reflect.TypeOf((*MockRepository)(nil).Unfollow), ctx, followerID, followingID)
}
