insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('CAP', 'D80518', '3458', 'https://a.espncdn.com/i/teamlogos/soccer/500/3458.png', 'Athletico-PR');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('AGO', 'FF0000', '10357', 'https://a.espncdn.com/i/teamlogos/soccer/500/10357.png', 'Atlético-GO');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('CAM', '000000', '7632', 'https://a.espncdn.com/i/teamlogos/soccer/500/7632.png', 'Atlético-MG');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('BAH', 'C60000', '9967', 'https://a.espncdn.com/i/teamlogos/soccer/500/9967.png', 'Bahia');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('BOT', '000000', '6086', 'https://a.espncdn.com/i/teamlogos/soccer/500/6086.png', 'Botafogo');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('COR', '000000', '874', 'https://a.espncdn.com/i/teamlogos/soccer/500/874.png', 'Corinthians');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('CRI', 'F8E71C', '9971', 'https://a.espncdn.com/i/teamlogos/soccer/500/9971.png', 'Criciúma');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('CRU', '0093EC', '2022', 'https://a.espncdn.com/i/teamlogos/soccer/500/2022.png', 'Cruzeiro');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('CUI', '004526', '17313', 'https://a.espncdn.com/i/teamlogos/soccer/500/17313.png', 'Cuiabá');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('FLA', 'C60000', '819', 'https://a.espncdn.com/i/teamlogos/soccer/500/819.png', 'Flamengo');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('FLU', '7E0202', '3445', 'https://a.espncdn.com/i/teamlogos/soccer/500/3445.png', 'Fluminense');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('FOR', '', '6272', 'https://a.espncdn.com/i/teamlogos/soccer/500/6272.png', 'Fortaleza');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('GRE', '0093EC', '6273', 'https://a.espncdn.com/i/teamlogos/soccer/500/6273.png', 'Grêmio');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('INT', 'C60000', '1936', 'https://a.espncdn.com/i/teamlogos/soccer/500/1936.png', 'Internacional');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('JUV', '417505', '6270', 'https://a.espncdn.com/i/teamlogos/soccer/500/6270.png', 'Juventude');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('PAL', '417505', '2029', 'https://a.espncdn.com/i/teamlogos/soccer/500/2029.png', 'Palmeiras');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('BRA', '000000', '6079', 'https://a.espncdn.com/i/teamlogos/soccer/500/6079.png', 'Red Bull Bragantino');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('SAO', 'C60000', '2026', 'https://a.espncdn.com/i/teamlogos/soccer/500/2026.png', 'São Paulo');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('VAS', '000000', '3454', 'https://a.espncdn.com/i/teamlogos/soccer/500/3454.png', 'Vasco da Gama');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('VIT', 'C6101C', '3457', 'https://a.espncdn.com/i/teamlogos/soccer/500/3457.png', 'Vitória');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('AMAZ', '000000', '21888', 'https://a.espncdn.com/i/teamlogos/soccer/500/21888.png', 'Amazonas');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('AMG', '417505', '6154', 'https://a.espncdn.com/i/teamlogos/soccer/500/6154.png', 'América-MG');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('AVA', '0093EC', '9966', 'https://a.espncdn.com/i/teamlogos/soccer/500/9966.png', 'Avaí');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('BFC', '000000', '10281', 'https://a.espncdn.com/i/teamlogos/soccer/500/10281.png', 'Botafogo SP');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('BRUS', 'C60000', '18428', 'https://a.espncdn.com/i/teamlogos/soccer/500/18428.png', 'Brusque');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('CRB', 'C60000', '9970', 'https://a.espncdn.com/i/teamlogos/soccer/500/9970.png', 'CRB');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('CEA', '010101', '9969', 'https://a.espncdn.com/i/teamlogos/soccer/500/9969.png', 'Ceará');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('CHA', '417505', '9318', 'https://a.espncdn.com/i/teamlogos/soccer/500/9318.png', 'Chapecoense');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('CFC', '417505', '3456', 'https://a.espncdn.com/i/teamlogos/soccer/500/3456.png', 'Coritiba');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('GOI', '417505', '3395', 'https://a.espncdn.com/i/teamlogos/soccer/500/3395.png', 'Goiás');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('GUA', '417505', '3448', 'https://a.espncdn.com/i/teamlogos/soccer/500/3448.png', 'Guarani');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('ITU', 'C60000', '4774', 'https://a.espncdn.com/i/teamlogos/soccer/500/4774.png', 'Ituano');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('MIR', 'FEDC00', '9169', 'https://a.espncdn.com/i/teamlogos/soccer/500/9169.png', 'Mirassol');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('NOV', '000000', '18127', 'https://a.espncdn.com/i/teamlogos/soccer/500/18127.png', 'Novorizontino');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('OPE', '000000', '18187', 'https://a.espncdn.com/i/teamlogos/soccer/500/18187.png', 'Operario PR');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('PAY', '0093EC', '15424', 'https://a.espncdn.com/i/teamlogos/soccer/500/15424.png', 'Paysandu');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('PON', '000000', '3459', 'https://a.espncdn.com/i/teamlogos/soccer/500/3459.png', 'Ponte Preta');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('SAN', '000000', '2674', 'https://a.espncdn.com/i/teamlogos/soccer/500/2674.png', 'Santos');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('SPO', 'C60000', '7635', 'https://a.espncdn.com/i/teamlogos/soccer/500/7635.png', 'Sport');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('VIL', 'C60000', '9973', 'https://a.espncdn.com/i/teamlogos/soccer/500/9973.png', 'Vila Nova-GO');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('ACMG', '000000', '20851', 'https://a.espncdn.com/i/teamlogos/soccer/500/20851.png', 'Athletic Club (Minas Gerais)');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('BPB', '020202', '17317', 'https://a.espncdn.com/i/teamlogos/soccer/500/17317.png', 'Botafogo-PB');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('FER', '7C3B3F', '18126', 'https://a.espncdn.com/i/teamlogos/soccer/500/18126.png', 'Ferroviária');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('LON', '0093EC', '17333', 'https://a.espncdn.com/i/teamlogos/soccer/500/17333.png', 'Londrina');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('REMO', '265891', '4936', 'https://a.espncdn.com/i/teamlogos/soccer/500/4936.png', 'Remo');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('BER', '000000', '11268', 'https://a.espncdn.com/i/teamlogos/soccer/500/11268.png', 'São Bernardo');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('VRE', '010101', '4806', 'https://a.espncdn.com/i/teamlogos/soccer/500/4806.png', 'Volta Redonda');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('YPI', 'FFD65A', '4935', 'https://a.espncdn.com/i/teamlogos/soccer/500/4935.png', 'Ypiranga');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('ABC', '000000', '9965', 'https://a.espncdn.com/i/teamlogos/soccer/500/9965.png', 'ABC');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('ASA', '000000', '6196', 'https://a.espncdn.com/i/teamlogos/soccer/500/6196.png', 'ASA');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('ADM', '000000', '15562', '', 'Aguia de Maraba');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('ARN', '000000', '7634', 'https://a.espncdn.com/i/teamlogos/soccer/500/7634.png', 'América-RN');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('ANA', '000000', '18424', 'https://a.espncdn.com/i/teamlogos/soccer/500/18424.png', 'Anápolis');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('APA', 'D4AE70', '18188', 'https://a.espncdn.com/i/teamlogos/soccer/500/18188.png', 'Aparecidense');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('RIO', '000000', '15502', '', 'Audax Rio');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('BRAS', 'FEC459', '9968', 'https://a.espncdn.com/i/teamlogos/soccer/500/9968.png', 'Brasiliense');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('CEOV', '000000', '20699', '', 'CEOV Operário');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('Capital FC', '000000', '22190', '', 'Capital FC');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('CSC', '000000', '20898', '', 'Cascavel');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('CAX', '1C60AA', '17131', 'https://a.espncdn.com/i/teamlogos/soccer/500/17131.png', 'Caxias do Sul');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('CIA', '1E2357', '4909', 'https://a.espncdn.com/i/teamlogos/soccer/500/4909.png', 'Cianorte');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('CON', '265891', '4875', 'https://a.espncdn.com/i/teamlogos/soccer/500/4875.png', 'Confiança');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('CREC', '000000', '21383', '', 'Costa Rica EC');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('FERR', '', '21901', '', 'Ferroviário');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('FEC', '000000', '21401', '', 'Fluminense PI');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('GA Sampaio', '000000', '22189', '', 'GA Sampaio');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('HUM', '000000', '21385', '', 'Humaita');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('IGU', '000000', '21865', '', 'Iguatu');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('Independente AP', '000000', '22193', '', 'Independente AP');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('ITA', '000000', '6214', 'https://a.espncdn.com/i/teamlogos/soccer/500/6214.png', 'Itabaiana');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('Itabuna', '000000', '22192', '', 'Itabuna');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('JAC', '000000', '17713', '', 'Jacuipense');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('Ji-Paraná FC', '000000', '22191', '', 'Ji-Paraná FC');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('Manauara', '000000', '22194', '', 'Manauara');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('MAR', '000000', '9303', '', 'Maranhao');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('MAR', '000000', '21864', '', 'Marcílio Dias');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('MAR', '000000', '17715', '', 'Maringá');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('MOT', '000000', '4908', 'https://a.espncdn.com/i/teamlogos/soccer/500/4908.png', 'Moto Club');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('MUR', '000000', '17722', 'https://a.espncdn.com/i/teamlogos/soccer/500/17722.png', 'Murici');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('NOV', 'fc7e01', '6087', 'https://a.espncdn.com/i/teamlogos/soccer/500/6087.png', 'Nova Iguaçu');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('NV', '000000', '21386', '', 'Nova Venécia');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('Olaria', '', '4787', '', 'Olaria');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('OMS', '000000', '19400', '', 'Operario MS');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('PVH', '000000', '20897', '', 'Porto Velho');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('Portuguesa S', '', '4785', '', 'Portuguesa Santista');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('POR', '2A8735', '18134', 'https://a.espncdn.com/i/teamlogos/soccer/500/18134.png', 'Portuguesa-RJ');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('RBS', '000000', '20894', '', 'Real Brasília');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('RNO', '000000', '17751', '', 'Real Noroeste');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('RET', '000000', '20896', '', 'Retró');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('RBR', 'C60000', '17319', 'https://a.espncdn.com/i/teamlogos/soccer/500/17319.png', 'Rio Branco FC');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('RAC', '000000', '17709', 'https://a.espncdn.com/i/teamlogos/soccer/500/17709.png', 'Ríver AC');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('SAM', 'FFD65A', '4873', 'https://a.espncdn.com/i/teamlogos/soccer/500/4873.png', 'Sampaio Corrêa');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('SEC', '000000', '15561', '', 'Sousa EC');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('SLU', 'C60000', '7391', 'https://a.espncdn.com/i/teamlogos/soccer/500/7391.png', 'São Luiz-RS');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('SRA', '01458E', '17723', 'https://a.espncdn.com/i/teamlogos/soccer/500/17723.png', 'São Raimundo-RR');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('TOC', '000000', '18192', '', 'Tocantinopolis');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('TOM', 'C60000', '17339', 'https://a.espncdn.com/i/teamlogos/soccer/500/17339.png', 'Tombense');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('TREM', '000000', '21553', '', 'Trem');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('TREZ', '000000', '4902', 'https://a.espncdn.com/i/teamlogos/soccer/500/4902.png', 'Treze');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('URMT', '000000', '4881', '', 'União Rondonópolis-MT');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('VNMG', 'C60000', '4910', 'https://a.espncdn.com/i/teamlogos/soccer/500/4910.png', 'Villa Nova-MG');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('AST', '000000', '18128', 'https://a.espncdn.com/i/teamlogos/soccer/500/18128.png', 'Água Santa');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('MIL', 'e4002b', '103', 'https://a.espncdn.com/i/teamlogos/soccer/500/103.png', 'AC Milan');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('MON', 'E91514', '174', 'https://a.espncdn.com/i/teamlogos/soccer/500/174.png', 'AS Mônaco');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('ARS', 'e20520', '359', 'https://a.espncdn.com/i/teamlogos/soccer/500/359.png', 'Arsenal');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('AVL', '660e36', '362', 'https://a.espncdn.com/i/teamlogos/soccer/500/362.png', 'Aston Villa');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('ATA', '1157bf', '105', 'https://a.espncdn.com/i/teamlogos/soccer/500/105.png', 'Atalanta');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('ATL', 'ca3624', '1068', 'https://a.espncdn.com/i/teamlogos/soccer/500/1068.png', 'Atlético de Madrid');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('BAR', '00529f', '83', 'https://a.espncdn.com/i/teamlogos/soccer/500/83.png', 'Barcelona');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('LEV', 'DA0308', '131', 'https://a.espncdn.com/i/teamlogos/soccer/500/131.png', 'Bayer Leverkusen');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('BMU', 'dc052d', '132', 'https://a.espncdn.com/i/teamlogos/soccer/500/132.png', 'Bayern de Munique ');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('BEN', 'ca281d', '1929', 'https://a.espncdn.com/i/teamlogos/soccer/500/1929.png', 'Benfica');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('BOL', '04043d', '107', 'https://a.espncdn.com/i/teamlogos/soccer/500/107.png', 'Bolonha');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('DOR', 'ffee00', '124', 'https://a.espncdn.com/i/teamlogos/soccer/500/124.png', 'Borussia Dortmund');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('BRS', 'ef2f24', '6997', 'https://a.espncdn.com/i/teamlogos/soccer/500/6997.png', 'Brest');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('CEL', '009921', '256', 'https://a.espncdn.com/i/teamlogos/soccer/500/256.png', 'Celtic');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('Club Brugge', '0081ff', '570', 'https://a.espncdn.com/i/teamlogos/soccer/500/570.png', 'Club Brugge');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('DZG', '0000bb', '597', 'https://a.espncdn.com/i/teamlogos/soccer/500/597.png', 'Dinamo Zagreb');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('FEY', 'ef2f24', '142', 'https://a.espncdn.com/i/teamlogos/soccer/500/142.png', 'Feyenoord Rotterdam');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('GRN', 'C60000', '9812', 'https://a.espncdn.com/i/teamlogos/soccer/500/9812.png', 'Girona');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('INT', '00239c', '110', 'https://a.espncdn.com/i/teamlogos/soccer/500/110.png', 'Internazionale');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('JUV', '000000', '111', 'https://a.espncdn.com/i/teamlogos/soccer/500/111.png', 'Juventus');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('LILL', 'c2051b', '166', 'https://a.espncdn.com/i/teamlogos/soccer/500/166.png', 'Lille');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('LIV', 'd11317', '364', 'https://a.espncdn.com/i/teamlogos/soccer/500/364.png', 'Liverpool');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('MCI', '99c5ea', '382', 'https://a.espncdn.com/i/teamlogos/soccer/500/382.png', 'Manchester City');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('PSV', 'ef2f24', '148', 'https://a.espncdn.com/i/teamlogos/soccer/500/148.png', 'PSV Eindhoven');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('PSG', '011F68', '160', 'https://a.espncdn.com/i/teamlogos/soccer/500/160.png', 'Paris Saint-Germain');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('RBL', 'ffffff', '11420', 'https://a.espncdn.com/i/teamlogos/soccer/500/11420.png', 'RB Leipzig');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('SLZ', 'd82c3a', '2790', 'https://a.espncdn.com/i/teamlogos/soccer/500/2790.png', 'RB Salzburg');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('RMD', 'ffffff', '86', 'https://a.espncdn.com/i/teamlogos/soccer/500/86.png', 'Real Madrid');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('RSB', 'FF0000', '2290', 'https://a.espncdn.com/i/teamlogos/soccer/500/2290.png', 'Red Star Belgrade');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('STG', 'ffffff', '3746', 'https://a.espncdn.com/i/teamlogos/soccer/500/3746.png', 'SK Sturm Graz');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('SHK', 'ff5900', '493', 'https://a.espncdn.com/i/teamlogos/soccer/500/493.png', 'Shakhtar Donetsk');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('SLB', '81c0ff', '521', 'https://a.espncdn.com/i/teamlogos/soccer/500/521.png', 'Slovan Bratislava');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('SPP', '791b29', '433', 'https://a.espncdn.com/i/teamlogos/soccer/500/433.png', 'Sparta Prague');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('SCP', '008127', '2250', 'https://a.espncdn.com/i/teamlogos/soccer/500/2250.png', 'Sporting CP');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('VFB', 'ffffff', '134', 'https://a.espncdn.com/i/teamlogos/soccer/500/134.png', 'VfB Stuttgart');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('YB', 'ffdd00', '2722', 'https://a.espncdn.com/i/teamlogos/soccer/500/2722.png', 'Young Boys');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('ROM', '990a2c', '104', 'https://a.espncdn.com/i/teamlogos/soccer/500/104.png', 'AS Roma');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('AZ', 'ef2f24', '140', 'https://a.espncdn.com/i/teamlogos/soccer/500/140.png', 'AZ Alkmaar');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('AJAX', 'DF1B27', '139', 'https://a.espncdn.com/i/teamlogos/soccer/500/139.png', 'Ajax');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('AND', '695196', '441', 'https://a.espncdn.com/i/teamlogos/soccer/500/441.png', 'Anderlecht');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('ATH', 'C8142F', '93', 'https://a.espncdn.com/i/teamlogos/soccer/500/93.png', 'Athletic Club');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('BES', 'ffffff', '1895', 'https://a.espncdn.com/i/teamlogos/soccer/500/1895.png', 'Besiktas');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('BODO', 'FCEE33', '2980', 'https://a.espncdn.com/i/teamlogos/soccer/500/2980.png', 'Bodo/Glimt');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('BRAG', 'de1f26', '2994', 'https://a.espncdn.com/i/teamlogos/soccer/500/2994.png', 'Braga');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('KYIV', 'ffffff', '440', 'https://a.espncdn.com/i/teamlogos/soccer/500/440.png', 'Dynamo Kyiv');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('FRA', 'ffffff', '125', 'https://a.espncdn.com/i/teamlogos/soccer/500/125.png', 'Eintracht Frankfurt');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('MID', '000000', '572', 'https://a.espncdn.com/i/teamlogos/soccer/500/572.png', 'FC Midtjylland');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('POR', '0000dd', '437', 'https://a.espncdn.com/i/teamlogos/soccer/500/437.png', 'FC Porto');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('TWE', 'F31522', '152', 'https://a.espncdn.com/i/teamlogos/soccer/500/152.png', 'FC Twente');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('FCSB', '0000dd', '484', 'https://a.espncdn.com/i/teamlogos/soccer/500/484.png', 'FCSB');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('FKQB', '000000', '10414', 'https://a.espncdn.com/i/teamlogos/soccer/500/10414.png', 'FK Qarabag');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('FEN', 'ffff00', '436', 'https://a.espncdn.com/i/teamlogos/soccer/500/436.png', 'Fenerbahçe');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('FER', '239B56', '622', 'https://a.espncdn.com/i/teamlogos/soccer/500/622.png', 'Ferencvaros');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('GAL', 'aa0031', '432', 'https://a.espncdn.com/i/teamlogos/soccer/500/432.png', 'Galatasaray');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('TSG', '003399', '7911', 'https://a.espncdn.com/i/teamlogos/soccer/500/7911.png', 'Hoffenheim');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('ELF', 'ffef32', '529', 'https://a.espncdn.com/i/teamlogos/soccer/500/529.png', 'IF Elfsborg');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('LUD', '008000', '13018', 'https://a.espncdn.com/i/teamlogos/soccer/500/13018.png', 'Ludogorets Razgrad');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('LYON', 'ffffff', '167', 'https://a.espncdn.com/i/teamlogos/soccer/500/167.png', 'Lyon');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('LAZ', '74bde7', '112', 'https://a.espncdn.com/i/teamlogos/soccer/500/112.png', 'Lázio');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('MTA', 'ffff00', '524', 'https://a.espncdn.com/i/teamlogos/soccer/500/524.png', 'Maccabi Tel-Aviv');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('MAL', '5699eb', '2720', 'https://a.espncdn.com/i/teamlogos/soccer/500/2720.png', 'Malmö FF');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('MUN', 'da020e', '360', 'https://a.espncdn.com/i/teamlogos/soccer/500/360.png', 'Manchester United');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('NICE', 'ef2f24', '2502', 'https://a.espncdn.com/i/teamlogos/soccer/500/2502.png', 'Nice');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('OLY', 'd01729', '435', 'https://a.espncdn.com/i/teamlogos/soccer/500/435.png', 'Olympiacos');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('PAOK', '000000', '605', 'https://a.espncdn.com/i/teamlogos/soccer/500/605.png', 'PAOK Salonika');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('RAN', '0046ff', '257', 'https://a.espncdn.com/i/teamlogos/soccer/500/257.png', 'Rangers');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('SOC', '3366CC', '89', 'https://a.espncdn.com/i/teamlogos/soccer/500/89.png', 'Real Sociedad');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('RFS', '0000dd', '12030', 'https://a.espncdn.com/i/teamlogos/soccer/500/12030.png', 'Rigas Futbola Skola');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('SLP', 'dc1f26', '494', 'https://a.espncdn.com/i/teamlogos/soccer/500/494.png', 'Slavia Prague');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('TOT', 'ffffff', '367', 'https://a.espncdn.com/i/teamlogos/soccer/500/367.png', 'Tottenham Hotspur');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('USG', 'FCEE33', '5807', 'https://a.espncdn.com/i/teamlogos/soccer/500/5807.png', 'Union St.-Gilloise');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('PLZ', '0000dd', '11706', 'https://a.espncdn.com/i/teamlogos/soccer/500/11706.png', 'Viktoria Plzen');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('ALE', '000000', '481', 'https://a.espncdn.com/i/teamlogos/countries/500/ger.png', 'Alemanha');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('ARG', '74acdf', '202', 'https://a.espncdn.com/i/teamlogos/countries/500/arg.png', 'Argentina');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('ARS', 'dddddd', '655', 'https://a.espncdn.com/i/teamlogos/countries/500/ksa.png', 'Arábia Saudita');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('AUS', '2a2d7c', '628', 'https://a.espncdn.com/i/teamlogos/countries/500/aus.png', 'Austrália');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('BRA', 'fee000', '205', 'https://a.espncdn.com/i/teamlogos/countries/500/bra.png', 'Brasil');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('BEL', 'ef3340', '459', 'https://a.espncdn.com/i/teamlogos/countries/500/bel.png', 'Bélgica');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('CMR', '197b63', '656', 'https://a.espncdn.com/i/teamlogos/countries/500/crm.png', 'Camarões');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('CAN', 'ed2224', '206', 'https://a.espncdn.com/i/teamlogos/countries/500/can.png', 'Canadá');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('KOR', 'ce2028', '451', 'https://a.espncdn.com/i/teamlogos/countries/500/kors.png', 'Coreia do Sul');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('CRC', 'ce1126', '214', 'https://a.espncdn.com/i/teamlogos/countries/500/crc.png', 'Costa Rica');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('CRO', 'ff0000', '477', 'https://a.espncdn.com/i/teamlogos/countries/500/cro.png', 'Croácia');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('DIN', 'd02a3e', '479', 'https://a.espncdn.com/i/teamlogos/countries/500/den.png', 'Dinamarca');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('EQU', 'ffdd00', '209', 'https://a.espncdn.com/i/teamlogos/countries/500/ecu.png', 'Equador');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('ESP', 'c60b1e', '164', 'https://a.espncdn.com/i/teamlogos/countries/500/esp.png', 'Espanha');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('USA', '213065', '660', 'https://a.espncdn.com/i/teamlogos/countries/500/usa.png', 'Estados Unidos');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('FRA', '0c2fff', '478', 'https://a.espncdn.com/i/teamlogos/countries/500/fra.png', 'França');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('GAN', 'ce2931', '4469', 'https://a.espncdn.com/i/teamlogos/countries/500/gha.png', 'Gana');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('HOL', 'fb5d00', '449', 'https://a.espncdn.com/i/teamlogos/countries/500/ned.png', 'Holanda');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('ENG', 'ffffff', '448', 'https://a.espncdn.com/i/teamlogos/countries/500/eng.png', 'Inglaterra');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('IRN', 'da0000', '469', 'https://a.espncdn.com/i/teamlogos/countries/500/irn.png', 'Irã');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('JPN', 'ed1c24', '627', 'https://a.espncdn.com/i/teamlogos/countries/500/jpn.png', 'Japão');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('MAR', '009060', '2869', 'https://a.espncdn.com/i/teamlogos/countries/500/mar.png', 'Marrocos');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('MEX', '006847', '203', 'https://a.espncdn.com/i/teamlogos/countries/500/mex.png', 'México');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('Gales', 'E70000', '578', 'https://a.espncdn.com/i/teamlogos/countries/500/wal.png', 'País de Gales');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('POL', 'ffffff', '471', 'https://a.espncdn.com/i/teamlogos/countries/500/pol.png', 'Polônia');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('Por', 'da291c', '482', 'https://a.espncdn.com/i/teamlogos/countries/500/por.png', 'Portugal');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('CAT', '691a40', '4398', 'https://a.espncdn.com/i/teamlogos/countries/500/qat.png', 'Qatar');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('SEN', '00853f', '654', 'https://a.espncdn.com/i/teamlogos/countries/500/sen.png', 'Senegal');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('SUI', 'd72b2c', '475', 'https://a.espncdn.com/i/teamlogos/countries/500/sui.png', 'Suíça');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('SRB', 'E70000', '6757', 'https://a.espncdn.com/i/teamlogos/countries/500/sba.png', 'Sérvia');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('TUN', 'D20300', '659', 'https://a.espncdn.com/i/teamlogos/countries/500/tun.png', 'Tunísia');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('URU', '003da5', '212', 'https://a.espncdn.com/i/teamlogos/countries/500/uru.png', 'Uruguai');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('CAB', '212121', '18995', 'https://a.espncdn.com/i/teamlogos/soccer/500/18995.png', 'Academia Puerto Cabello');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('ALM', '0000ff', '2680', 'https://a.espncdn.com/i/teamlogos/soccer/500/2680.png', 'Alianza Lima');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('CAR', 'ff0000', '19425', 'https://a.espncdn.com/i/teamlogos/soccer/500/19425.png', 'Always Ready');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('JUN', 'C60000', '4815', 'https://a.espncdn.com/i/teamlogos/soccer/500/4815.png', 'Atlético Junior');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('NAL', '06933c', '5264', 'https://a.espncdn.com/i/teamlogos/soccer/500/5264.png', 'Atlético Nacional');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('AUR', '00aae4', '6046', 'https://a.espncdn.com/i/teamlogos/soccer/500/6046.png', 'Aurora');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('BAR', 'ffff00', '2686', 'https://a.espncdn.com/i/teamlogos/soccer/500/2686.png', 'Barcelona SC');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('BOL', '3c96c4', '2681', 'https://a.espncdn.com/i/teamlogos/soccer/500/2681.png', 'Bolívar');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('CAR', 'E22B2D', '4811', 'https://a.espncdn.com/i/teamlogos/soccer/500/4811.png', 'Caracas FC');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('CPT', 'EF2D24', '2671', 'https://a.espncdn.com/i/teamlogos/soccer/500/2671.png', 'Cerro Porteño');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('COB', 'fd0000', '4133', 'https://a.espncdn.com/i/teamlogos/soccer/500/4133.png', 'Cobresal');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('COL', '050505', '2688', 'https://a.espncdn.com/i/teamlogos/soccer/500/2688.png', 'Colo Colo');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('DTC', '1a1a1a', '4818', 'https://a.espncdn.com/i/teamlogos/soccer/500/4818.png', 'Deportivo Táchira');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('ELN', 'f60404', '882', 'https://a.espncdn.com/i/teamlogos/soccer/500/882.png', 'El Nacional');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('EST', 'C60000', '8', 'https://a.espncdn.com/i/teamlogos/soccer/500/8.png', 'Estudiantes de La Plata');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('GCM', '0060f0', '6756', 'https://a.espncdn.com/i/teamlogos/soccer/500/6756.png', 'Godoy Cruz Antonio Tomba');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('HUA', '023396', '4134', 'https://a.espncdn.com/i/teamlogos/soccer/500/4134.png', 'Huachipato');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('IDV', '000D5D', '17086', 'https://a.espncdn.com/i/teamlogos/soccer/500/17086.png', 'Independiente del Valle');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('LIB', '212121', '2670', 'https://a.espncdn.com/i/teamlogos/soccer/500/2670.png', 'Libertad');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('LDU', '1c1d5c', '4816', 'https://a.espncdn.com/i/teamlogos/soccer/500/4816.png', 'Liga de Quito');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('LIV', 'C60000', '5492', 'https://a.espncdn.com/i/teamlogos/soccer/500/5492.png', 'Liverpool');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('MIL', '0202db', '5484', 'https://a.espncdn.com/i/teamlogos/soccer/500/5484.png', 'Millonarios');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('NAC', '7CBDE7', '5584', 'https://a.espncdn.com/i/teamlogos/soccer/500/5584.png', 'Nacional');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('NAC', '345BBC', '2684', 'https://a.espncdn.com/i/teamlogos/soccer/500/2684.png', 'Nacional');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('PAL', '2a1b07', '4422', 'https://a.espncdn.com/i/teamlogos/soccer/500/4422.png', 'Palestino');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('PEN', '000000', '2683', 'https://a.espncdn.com/i/teamlogos/soccer/500/2683.png', 'Peñarol');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('POR', '010101', '6762', 'https://a.espncdn.com/i/teamlogos/soccer/500/6762.png', 'Portuguesa');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('RIV', 'C60000', '16', 'https://a.espncdn.com/i/teamlogos/soccer/500/16.png', 'River Plate');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('ROS', 'ffff00', '17', 'https://a.espncdn.com/i/teamlogos/soccer/500/17.png', 'Rosário Central');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('SLZ', '0060f0', '18', 'https://a.espncdn.com/i/teamlogos/soccer/500/18.png', 'San Lorenzo');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('SCR', '3bb8e2', '2673', 'https://a.espncdn.com/i/teamlogos/soccer/500/2673.png', 'Sporting Cristal');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('TALL', '000000', '19', 'https://a.espncdn.com/i/teamlogos/soccer/500/19.png', 'Talleres (Córdoba)');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('STR', '000000', '2687', 'https://a.espncdn.com/i/teamlogos/soccer/500/2687.png', 'The Strongest');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('TRI', '000000', '7466', 'https://a.espncdn.com/i/teamlogos/soccer/500/7466.png', 'Trinidense');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('UNI', 'ffffbf', '2685', 'https://a.espncdn.com/i/teamlogos/soccer/500/2685.png', 'Universitario');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('AGD', 'ffff00', '9762', 'https://a.espncdn.com/i/teamlogos/soccer/500/9762.png', 'Águilas Doradas');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('AFC', '000000', '9761', 'https://a.espncdn.com/i/teamlogos/soccer/500/9761.png', 'Alianza FC');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('ARGJ', 'C60000', '3', 'https://a.espncdn.com/i/teamlogos/soccer/500/3.png', 'Argentinos Juniors');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('BEL', '0060f0', '4', 'https://a.espncdn.com/i/teamlogos/soccer/500/4.png', 'Belgrano (Córdoba)');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('CABJ', 'fcb000', '5', 'https://a.espncdn.com/i/teamlogos/soccer/500/5.png', 'Boca Juniors');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('COQ', '000000', '8186', 'https://a.espncdn.com/i/teamlogos/soccer/500/8186.png', 'Coquimbo Unido');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('CVL', '000000', '5567', 'https://a.espncdn.com/i/teamlogos/soccer/500/5567.png', 'César Vallejo');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('DAN', '0a0a0a', '4817', 'https://a.espncdn.com/i/teamlogos/soccer/500/4817.png', 'Danubio');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('DYJ', 'ffff00', '8950', 'https://a.espncdn.com/i/teamlogos/soccer/500/8950.png', 'Defensa y Justicia');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('DEL', '212121', '1011', 'https://a.espncdn.com/i/teamlogos/soccer/500/1011.png', 'Delfín');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('GAR', '000000', '21819', 'https://a.espncdn.com/i/teamlogos/soccer/500/21819.png', 'Deportivo Garcilaso');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('RZU', '0000ff', '21850', 'https://a.espncdn.com/i/teamlogos/soccer/500/21850.png', 'Deportivo Rayo Zuliano');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('DIM', 'd70000', '2690', 'https://a.espncdn.com/i/teamlogos/soccer/500/2690.png', 'Independiente Medellín');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('LAN', '9f0000', '12', 'https://a.espncdn.com/i/teamlogos/soccer/500/12.png', 'Lanús');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('MET', '000000', '13481', 'https://a.espncdn.com/i/teamlogos/soccer/500/13481.png', 'Metropolitanos FC');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('POT', '212121', '10311', 'https://a.espncdn.com/i/teamlogos/soccer/500/10311.png', 'Nacional Potosí');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('RAC', '107436', '9903', 'https://a.espncdn.com/i/teamlogos/soccer/500/9903.png', 'Racing (Montevideo)');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('RAC', '409fff', '15', 'https://a.espncdn.com/i/teamlogos/soccer/500/15.png', 'Racing Club');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('TOM', '000000', '20890', 'https://a.espncdn.com/i/teamlogos/soccer/500/20890.png', 'Real Tomayapo');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('SPA', '000000', '21313', 'https://a.espncdn.com/i/teamlogos/soccer/500/21313.png', 'Sportivo Ameliano');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('LUQ', '212121', '5583', 'https://a.espncdn.com/i/teamlogos/soccer/500/5583.png', 'Sportivo Luqueño');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('UCA', '0a4f8d', '9283', 'https://a.espncdn.com/i/teamlogos/soccer/500/9283.png', 'Universidad Católica (Quito)');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('ULC', 'fd0000', '10144', 'https://a.espncdn.com/i/teamlogos/soccer/500/10144.png', 'Unión La Calera');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('BOU', 'f42727', '349', 'https://a.espncdn.com/i/teamlogos/soccer/500/349.png', 'AFC Bournemouth');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('BRN', 'f42727', '337', 'https://a.espncdn.com/i/teamlogos/soccer/500/337.png', 'Brentford');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('BHA', '0606fa', '331', 'https://a.espncdn.com/i/teamlogos/soccer/500/331.png', 'Brighton & Hove Albion');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('CHE', '144992', '363', 'https://a.espncdn.com/i/teamlogos/soccer/500/363.png', 'Chelsea');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('CRY', '0202fb', '384', 'https://a.espncdn.com/i/teamlogos/soccer/500/384.png', 'Crystal Palace');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('EVE', '0606fa', '368', 'https://a.espncdn.com/i/teamlogos/soccer/500/368.png', 'Everton');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('FUL', 'ffffff', '370', 'https://a.espncdn.com/i/teamlogos/soccer/500/370.png', 'Fulham');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('IPS', '0000fa', '373', 'https://a.espncdn.com/i/teamlogos/soccer/500/373.png', 'Ipswich Town');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('LEC', '0202fb', '375', 'https://a.espncdn.com/i/teamlogos/soccer/500/375.png', 'Leicester City');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('NEW', '000000', '361', 'https://a.espncdn.com/i/teamlogos/soccer/500/361.png', 'Newcastle United');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('FOR', 'c8102e', '393', 'https://a.espncdn.com/i/teamlogos/soccer/500/393.png', 'Nottingham Forest');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('SOU', 'ED1A3B', '376', 'https://a.espncdn.com/i/teamlogos/soccer/500/376.png', 'Southampton');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('WHU', '7c2c3b', '371', 'https://a.espncdn.com/i/teamlogos/soccer/500/371.png', 'West Ham United');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('WOL', 'fdb913', '380', 'https://a.espncdn.com/i/teamlogos/soccer/500/380.png', 'Wolverhampton Wanderers');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('BLK', '0000fa', '365', 'https://a.espncdn.com/i/teamlogos/soccer/500/365.png', 'Blackburn Rovers');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('BRC', 'f42727', '333', 'https://a.espncdn.com/i/teamlogos/soccer/500/333.png', 'Bristol City');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('BRN', '6C1D45', '379', 'https://a.espncdn.com/i/teamlogos/soccer/500/379.png', 'Burnley');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('CAR', '0000fa', '347', 'https://a.espncdn.com/i/teamlogos/soccer/500/347.png', 'Cardiff City');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('Conventry', '87cced', '388', 'https://a.espncdn.com/i/teamlogos/soccer/500/388.png', 'Conventry City');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('DER', 'ffffff', '374', 'https://a.espncdn.com/i/teamlogos/soccer/500/374.png', 'Derby County');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('HCY', 'f28800', '306', 'https://a.espncdn.com/i/teamlogos/soccer/500/306.png', 'Hull City');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('LEE', 'ffffff', '357', 'https://a.espncdn.com/i/teamlogos/soccer/500/357.png', 'Leeds United');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('LTN', 'ff4f00', '301', 'https://a.espncdn.com/i/teamlogos/soccer/500/301.png', 'Luton Town');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('MID', 'f42727', '369', 'https://a.espncdn.com/i/teamlogos/soccer/500/369.png', 'Middlesbrough');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('MIL', '091453', '391', 'https://a.espncdn.com/i/teamlogos/soccer/500/391.png', 'Millwall');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('NOR', 'ffff00', '381', 'https://a.espncdn.com/i/teamlogos/soccer/500/381.png', 'Norwich City');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('OXF', 'ffff00', '311', 'https://a.espncdn.com/i/teamlogos/soccer/500/311.png', 'Oxford United');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('PLY', '003e00', '307', 'https://a.espncdn.com/i/teamlogos/soccer/500/307.png', 'Plymouth Argyle');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('POR', '0000fa', '385', 'https://a.espncdn.com/i/teamlogos/soccer/500/385.png', 'Portsmouth');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('PNE', 'ffffff', '394', 'https://a.espncdn.com/i/teamlogos/soccer/500/394.png', 'Preston North End');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('QPR', '0000d4', '334', 'https://a.espncdn.com/i/teamlogos/soccer/500/334.png', 'Queens Park Rangers');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('SHU', 'f42727', '398', 'https://a.espncdn.com/i/teamlogos/soccer/500/398.png', 'Sheffield United');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('SHW', '0000ff', '399', 'https://a.espncdn.com/i/teamlogos/soccer/500/399.png', 'Sheffield Wednesday');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('STK', 'f42727', '336', 'https://a.espncdn.com/i/teamlogos/soccer/500/336.png', 'Stoke City');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('SUN', 'EB172B', '366', 'https://a.espncdn.com/i/teamlogos/soccer/500/366.png', 'Sunderland');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('SWA', 'ffffff', '318', 'https://a.espncdn.com/i/teamlogos/soccer/500/318.png', 'Swansea City');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('WAT', 'ffff00', '395', 'https://a.espncdn.com/i/teamlogos/soccer/500/395.png', 'Watford');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('WBA', '091453', '383', 'https://a.espncdn.com/i/teamlogos/soccer/500/383.png', 'West Bromwich Albion');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('Alavés', '0000ff', '96', 'https://a.espncdn.com/i/teamlogos/soccer/500/96.png', 'Alavés');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('VIG', '6cace4', '85', 'https://a.espncdn.com/i/teamlogos/soccer/500/85.png', 'Celta de Vigo');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('ESP', '3366CC', '88', 'https://a.espncdn.com/i/teamlogos/soccer/500/88.png', 'Espanyol');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('GET', '0000ff', '2922', 'https://a.espncdn.com/i/teamlogos/soccer/500/2922.png', 'Getafe');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('PAL', 'ffff00', '98', 'https://a.espncdn.com/i/teamlogos/soccer/500/98.png', 'Las Palmas');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('LGN', '6cace4', '17534', 'https://a.espncdn.com/i/teamlogos/soccer/500/17534.png', 'Leganés');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('MLA', 'C8142F', '84', 'https://a.espncdn.com/i/teamlogos/soccer/500/84.png', 'Mallorca');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('OSA', 'cd0000', '97', 'https://a.espncdn.com/i/teamlogos/soccer/500/97.png', 'Osasuna');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('RAY', 'ffffff', '101', 'https://a.espncdn.com/i/teamlogos/soccer/500/101.png', 'Rayo Vallecano');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('RBT', '288A00', '244', 'https://a.espncdn.com/i/teamlogos/soccer/500/244.png', 'Real Betis');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('VLD', '7a2d9d', '95', 'https://a.espncdn.com/i/teamlogos/soccer/500/95.png', 'Real Valladolid');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('SEV', 'ffffff', '243', 'https://a.espncdn.com/i/teamlogos/soccer/500/243.png', 'Sevilla FC');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('VAL', 'ffffff', '94', 'https://a.espncdn.com/i/teamlogos/soccer/500/94.png', 'Valencia');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('VLR', 'ffff00', '102', 'https://a.espncdn.com/i/teamlogos/soccer/500/102.png', 'Villareal');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('Albacete', 'BC0814', '2737', 'https://a.espncdn.com/i/teamlogos/soccer/500/2737.png', 'Albacete');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('ALM', 'C8142F', '6832', 'https://a.espncdn.com/i/teamlogos/soccer/500/6832.png', 'Almería');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('BUR', '000000', '12597', 'https://a.espncdn.com/i/teamlogos/soccer/500/12597.png', 'Burgos');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('CAS', '000000', '4438', 'https://a.espncdn.com/i/teamlogos/soccer/500/4438.png', 'Castellón');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('CAD', 'ffff00', '3842', 'https://a.espncdn.com/i/teamlogos/soccer/500/3842.png', 'Cádiz');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('COR', '288A00', '8447', 'https://a.espncdn.com/i/teamlogos/soccer/500/8447.png', 'Córdoba');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('DEP', '3366CC', '90', 'https://a.espncdn.com/i/teamlogos/soccer/500/90.png', 'Deportivo La Coruña');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('EIB', 'c00000', '3752', 'https://a.espncdn.com/i/teamlogos/soccer/500/3752.png', 'Eibar');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('ELC', 'ffffff', '3751', 'https://a.espncdn.com/i/teamlogos/soccer/500/3751.png', 'Elche');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('ELD', '000000', '7320', 'https://a.espncdn.com/i/teamlogos/soccer/500/7320.png', 'Eldense');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('CAR', '000000', '5419', 'https://a.espncdn.com/i/teamlogos/soccer/500/5419.png', 'FC Cartagena');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('GRN', 'C8142F', '3747', 'https://a.espncdn.com/i/teamlogos/soccer/500/3747.png', 'Granada');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('HUE', '000099', '5413', 'https://a.espncdn.com/i/teamlogos/soccer/500/5413.png', 'Huesca');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('LEV', 'C8142F', '1538', 'https://a.espncdn.com/i/teamlogos/soccer/500/1538.png', 'Levante');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('MIR', '000000', '4515', 'https://a.espncdn.com/i/teamlogos/soccer/500/4515.png', 'Mirandés');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('MGA', 'b9e8f0', '99', 'https://a.espncdn.com/i/teamlogos/soccer/500/99.png', 'Málaga');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('FER', '000000', '8448', 'https://a.espncdn.com/i/teamlogos/soccer/500/8448.png', 'Racing Ferrol');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('RAC', '3B6C1A', '87', 'https://a.espncdn.com/i/teamlogos/soccer/500/87.png', 'Racing Santander');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('OVI', '000000', '92', 'https://a.espncdn.com/i/teamlogos/soccer/500/92.png', 'Real Oviedo');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('ZAR', '000099', '91', 'https://a.espncdn.com/i/teamlogos/soccer/500/91.png', 'Real Zaragoza');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('GIJ', 'C8142F', '3788', 'https://a.espncdn.com/i/teamlogos/soccer/500/3788.png', 'Sporting Gijón');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('TEN', '008bc4', '245', 'https://a.espncdn.com/i/teamlogos/soccer/500/245.png', 'Tenerife');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('AUX', 'ffffff', '172', 'https://a.espncdn.com/i/teamlogos/soccer/500/172.png', 'AJ Auxerre');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('ANG', '1a1a1a', '7868', 'https://a.espncdn.com/i/teamlogos/soccer/500/7868.png', 'Angers');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('LEH', '011F68', '3236', 'https://a.espncdn.com/i/teamlogos/soccer/500/3236.png', 'Le Havre AC');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('LNS', 'E91514', '175', 'https://a.espncdn.com/i/teamlogos/soccer/500/175.png', 'Lens');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('OLM', 'ffffff', '176', 'https://a.espncdn.com/i/teamlogos/soccer/500/176.png', 'Marseille');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('MON', '011F68', '274', 'https://a.espncdn.com/i/teamlogos/soccer/500/274.png', 'Montpellier');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('NAN', 'ffff00', '165', 'https://a.espncdn.com/i/teamlogos/soccer/500/165.png', 'Nantes');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('ASSE', '51cc5f', '178', 'https://a.espncdn.com/i/teamlogos/soccer/500/178.png', 'Saint-Etienne');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('REN', 'ef2f24', '169', 'https://a.espncdn.com/i/teamlogos/soccer/500/169.png', 'Stade Rennais');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('REIM', 'ef2f24', '3243', 'https://a.espncdn.com/i/teamlogos/soccer/500/3243.png', 'Stade de Reims');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('STR', '0000bf', '180', 'https://a.espncdn.com/i/teamlogos/soccer/500/180.png', 'Strasbourg');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('TOU', '560080', '179', 'https://a.espncdn.com/i/teamlogos/soccer/500/179.png', 'Toulouse');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('HDH', 'DA0308', '6418', 'https://a.espncdn.com/i/teamlogos/soccer/500/6418.png', '1. FC Heidenheim 1846');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('AUG', 'ffffff', '3841', 'https://a.espncdn.com/i/teamlogos/soccer/500/3841.png', 'Augsburg');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('MGB', 'ffffff', '268', 'https://a.espncdn.com/i/teamlogos/soccer/500/268.png', 'Borussia Monchengladbach');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('SCF', 'DA0308', '126', 'https://a.espncdn.com/i/teamlogos/soccer/500/126.png', 'Freiburg');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('KSV', '0754ba', '7884', 'https://a.espncdn.com/i/teamlogos/soccer/500/7884.png', 'Holstein Kiel');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('M05', 'DA0308', '2950', 'https://a.espncdn.com/i/teamlogos/soccer/500/2950.png', 'Mainz');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('STP', '442e23', '270', 'https://a.espncdn.com/i/teamlogos/soccer/500/270.png', 'St Pauli');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('FCU', 'DA0308', '598', 'https://a.espncdn.com/i/teamlogos/soccer/500/598.png', 'Union Berlin');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('BOC', '000055', '121', 'https://a.espncdn.com/i/teamlogos/soccer/500/121.png', 'VfL Bochum');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('WBR', '03915c', '137', 'https://a.espncdn.com/i/teamlogos/soccer/500/137.png', 'Werder Bremen');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('WLF', '81f733', '138', 'https://a.espncdn.com/i/teamlogos/soccer/500/138.png', 'Wolfsburg');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('FCM', '0068B2', '10382', 'https://a.espncdn.com/i/teamlogos/soccer/500/10382.png', '1. FC Magdeburg');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('FCN', '9f0000', '269', 'https://a.espncdn.com/i/teamlogos/soccer/500/269.png', '1. FC Nürnberg');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('KOE', 'ffffff', '122', 'https://a.espncdn.com/i/teamlogos/soccer/500/122.png', 'Colônia');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('FDD', 'ffffff', '9707', 'https://a.espncdn.com/i/teamlogos/soccer/500/9707.png', 'Fortuna Düsseldorf');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('HSV', '1a26af', '127', 'https://a.espncdn.com/i/teamlogos/soccer/500/127.png', 'Hamburg SV');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('H96', '179D33', '2428', 'https://a.espncdn.com/i/teamlogos/soccer/500/2428.png', 'Hannover 96');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('BSC', '0000dd', '129', 'https://a.espncdn.com/i/teamlogos/soccer/500/129.png', 'Hertha Berlin');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('KSL', '8C273D', '130', 'https://a.espncdn.com/i/teamlogos/soccer/500/130.png', 'Kaiserslautern');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('KSC', '2563B8', '4471', 'https://a.espncdn.com/i/teamlogos/soccer/500/4471.png', 'Karlsruher SC');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('PAD', '0000dd', '3307', 'https://a.espncdn.com/i/teamlogos/soccer/500/3307.png', 'Paderborn');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('PRM', '000000', '9867', 'https://a.espncdn.com/i/teamlogos/soccer/500/9867.png', 'Preußen Münster');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('REG', 'ce1b0e', '11017', 'https://a.espncdn.com/i/teamlogos/soccer/500/11017.png', 'SSV Jahn Regensburg');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('ULM', '000000', '15710', 'https://a.espncdn.com/i/teamlogos/soccer/500/15710.png', 'SSV Ulm 1846');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('ELV', '000000', '10388', 'https://a.espncdn.com/i/teamlogos/soccer/500/10388.png', 'SV 07 Elversberg');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('SVD', '003399', '3812', 'https://a.espncdn.com/i/teamlogos/soccer/500/3812.png', 'SV Darmstadt 98');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('S04', '0000dd', '133', 'https://a.espncdn.com/i/teamlogos/soccer/500/133.png', 'Schalke 04');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('FUR', '288A00', '3070', 'https://a.espncdn.com/i/teamlogos/soccer/500/3070.png', 'SpVgg Greuther Fürth');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('EBS', 'ffde16', '3067', 'https://a.espncdn.com/i/teamlogos/soccer/500/3067.png', 'TSV Eintracht Braunschweig');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('CAG', '282846', '2925', 'https://a.espncdn.com/i/teamlogos/soccer/500/2925.png', 'Cagliari');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('COMO', '3933FF', '2572', 'https://a.espncdn.com/i/teamlogos/soccer/500/2572.png', 'Como');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('EMP', '005bdd', '2574', 'https://a.espncdn.com/i/teamlogos/soccer/500/2574.png', 'Empoli');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('FIO', '4c1d84', '109', 'https://a.espncdn.com/i/teamlogos/soccer/500/109.png', 'Fiorentina');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('GEN', '08305d', '3263', 'https://a.espncdn.com/i/teamlogos/soccer/500/3263.png', 'Genoa');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('HEL', '00239c', '119', 'https://a.espncdn.com/i/teamlogos/soccer/500/119.png', 'Hellas Verona');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('LEC', 'e4002b', '113', 'https://a.espncdn.com/i/teamlogos/soccer/500/113.png', 'Lecce');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('MON', 'C8142F', '4007', 'https://a.espncdn.com/i/teamlogos/soccer/500/4007.png', 'Monza');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('NAP', '0677d2', '114', 'https://a.espncdn.com/i/teamlogos/soccer/500/114.png', 'Napoli');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('PAR', '19161D', '115', 'https://a.espncdn.com/i/teamlogos/soccer/500/115.png', 'Parma');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('TOR', '9f0000', '239', 'https://a.espncdn.com/i/teamlogos/soccer/500/239.png', 'Torino');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('UDI', '19161D', '118', 'https://a.espncdn.com/i/teamlogos/soccer/500/118.png', 'Udinese');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('VEN', '000000', '17530', 'https://a.espncdn.com/i/teamlogos/soccer/500/17530.png', 'Venezia');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('BAR', 'aa0001', '106', 'https://a.espncdn.com/i/teamlogos/soccer/500/106.png', 'Bari');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('BRS', '006bb9', '108', 'https://a.espncdn.com/i/teamlogos/soccer/500/108.png', 'Brescia');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('CAR', '000000', '3988', 'https://a.espncdn.com/i/teamlogos/soccer/500/3988.png', 'Carrarese');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('CAT', '000000', '3257', 'https://a.espncdn.com/i/teamlogos/soccer/500/3257.png', 'Catanzaro');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('CES', '1a1a1a', '3337', 'https://a.espncdn.com/i/teamlogos/soccer/500/3337.png', 'Cesena');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('CIT', '990000', '3943', 'https://a.espncdn.com/i/teamlogos/soccer/500/3943.png', 'Cittadella');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('COS', '000066', '8683', 'https://a.espncdn.com/i/teamlogos/soccer/500/8683.png', 'Cosenza');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('CRE', 'FF0000', '4050', 'https://a.espncdn.com/i/teamlogos/soccer/500/4050.png', 'Cremonese');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('FRO', 'ffff00', '4057', 'https://a.espncdn.com/i/teamlogos/soccer/500/4057.png', 'Frosinone');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('JVS', '000000', '3975', 'https://a.espncdn.com/i/teamlogos/soccer/500/3975.png', 'Juve Stabia');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('Mantova', '', '3991', 'https://a.espncdn.com/i/teamlogos/soccer/500/3991.png', 'Mantova');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('MOD', '000000', '2573', 'https://a.espncdn.com/i/teamlogos/soccer/500/2573.png', 'Modena');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('PAL', 'F9BED4', '2923', 'https://a.espncdn.com/i/teamlogos/soccer/500/2923.png', 'Palermo');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('PIS', '1a1a1a', '3956', 'https://a.espncdn.com/i/teamlogos/soccer/500/3956.png', 'Pisa');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('REG', '000000', '3942', 'https://a.espncdn.com/i/teamlogos/soccer/500/3942.png', 'Reggiana');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('SAL', '990000', '3240', 'https://a.espncdn.com/i/teamlogos/soccer/500/3240.png', 'Salernitana');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('SMP', '2234a4', '2734', 'https://a.espncdn.com/i/teamlogos/soccer/500/2734.png', 'Sampdoria');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('SAS', '0fa653', '3997', 'https://a.espncdn.com/i/teamlogos/soccer/500/3997.png', 'Sassuolo');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('SPE', 'ffffff', '4056', 'https://a.espncdn.com/i/teamlogos/soccer/500/4056.png', 'Spezia');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('SUD', '000000', '11139', 'https://a.espncdn.com/i/teamlogos/soccer/500/11139.png', 'Suditrol');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('AVS', '000000', '22064', 'https://a.espncdn.com/i/teamlogos/soccer/500/22064.png', 'AVS');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('ARO', 'ffea01', '15784', 'https://a.espncdn.com/i/teamlogos/soccer/500/15784.png', 'Arouca');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('BOA', '1a1a1a', '2256', 'https://a.espncdn.com/i/teamlogos/soccer/500/2256.png', 'Boavista');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('CDN', '000000', '3472', 'https://a.espncdn.com/i/teamlogos/soccer/500/3472.png', 'C.D. Nacional');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('CAS', '000000', '21581', 'https://a.espncdn.com/i/teamlogos/soccer/500/21581.png', 'Casa Pia');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('EST', 'ffea01', '12216', 'https://a.espncdn.com/i/teamlogos/soccer/500/12216.png', 'Estoril');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('EST', '000000', '21610', 'https://a.espncdn.com/i/teamlogos/soccer/500/21610.png', 'Estrela');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('FAM', 'FFFFFF', '12698', 'https://a.espncdn.com/i/teamlogos/soccer/500/12698.png', 'FC Famalicao');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('GVFC', 'de1f26', '3699', 'https://a.espncdn.com/i/teamlogos/soccer/500/3699.png', 'Gil Vicente');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('GUI', 'ffffff', '5309', 'https://a.espncdn.com/i/teamlogos/soccer/500/5309.png', 'Guimaraes');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('MOR', '288A00', '3696', 'https://a.espncdn.com/i/teamlogos/soccer/500/3696.png', 'Moreirense');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('RIO', '3b8649', '3822', 'https://a.espncdn.com/i/teamlogos/soccer/500/3822.png', 'Rio Ave');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('SCF', '000000', '20740', 'https://a.espncdn.com/i/teamlogos/soccer/500/20740.png', 'SC Farense');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('SCL', 'C60000', '12215', 'https://a.espncdn.com/i/teamlogos/soccer/500/12215.png', 'Santa Clara');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('ILI', '000000', '18963', 'https://a.espncdn.com/i/teamlogos/soccer/500/18963.png', 'Inter de Limeira');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('PTG', '417505', '4773', 'https://a.espncdn.com/i/teamlogos/soccer/500/4773.png', 'Portuguesa');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('STA', 'FEDC00', '17720', 'https://a.espncdn.com/i/teamlogos/soccer/500/17720.png', 'Santo André');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('BAN', 'C60000', '10265', 'https://a.espncdn.com/i/teamlogos/soccer/500/10265.png', 'Bangu');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('BVT', '87764e', '900', 'https://a.espncdn.com/i/teamlogos/soccer/500/900.png', 'Boavista');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('MAD', '6F1628', '4786', 'https://a.espncdn.com/i/teamlogos/soccer/500/4786.png', 'Madureira');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('SCFE', 'ffbf00', '20855', '', 'Sampaio Correa RJ');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('AVE', '3B5B4C', '10266', 'https://a.espncdn.com/i/teamlogos/soccer/500/10266.png', 'Avenida');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('BRS', 'df392f', '17134', 'https://a.espncdn.com/i/teamlogos/soccer/500/17134.png', 'Brasil de Pelotas');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('GDB', '000000', '21369', '', 'Guarany de Bagé');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('NVH', '0093EC', '7388', 'https://a.espncdn.com/i/teamlogos/soccer/500/7388.png', 'Novo Hamburgo');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('STC', '000000', '20899', '', 'Santa Cruz (RS)');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('SJO', '020042', '7389', 'https://a.espncdn.com/i/teamlogos/soccer/500/7389.png', 'São José-RS');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('DEM', '000000', '18396', 'https://a.espncdn.com/i/teamlogos/soccer/500/18396.png', 'Democrata GV');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('IPA', '4CBB17', '4905', '', 'Ipatinga');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('ITA', '000000', '22142', '', 'Itabirito');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('PAT', '945E22', '18900', 'https://a.espncdn.com/i/teamlogos/soccer/500/18900.png', 'Patrocinense');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('POU', '000000', '20852', '', 'Pouso Alegre');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('UBE', '417505', '9460', 'https://a.espncdn.com/i/teamlogos/soccer/500/9460.png', 'Uberlândia');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('ALT', '000000', '18433', '', 'Altos');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('JUA', '000000', '18191', 'https://a.espncdn.com/i/teamlogos/soccer/500/18191.png', 'Juazeirense');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('NAU', 'C60000', '7633', 'https://a.espncdn.com/i/teamlogos/soccer/500/7633.png', 'Náutico');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('ALB', 'E70000', '585', 'https://a.espncdn.com/i/teamlogos/countries/500/alb.png', 'Albania');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('AND', 'E70000', '587', 'https://a.espncdn.com/i/teamlogos/countries/500/and.png', 'Andorra');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('ARM', 'DE2400', '579', 'https://a.espncdn.com/i/teamlogos/countries/500/fifa.armenia.png', 'Armênia');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('AZE', '2D4AB0', '581', 'https://a.espncdn.com/i/teamlogos/countries/500/aze.png', 'Azerbaijão');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('BLR', 'ffffff', '583', 'https://a.espncdn.com/i/teamlogos/countries/500/blr.png', 'Bielorússia');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('BUL', 'd62612', '462', 'https://a.espncdn.com/i/teamlogos/countries/500/bul.png', 'Bulgária');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('BIH', '112855', '452', 'https://a.espncdn.com/i/teamlogos/countries/500/bih.png', 'Bósnia e Herzegovina');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('CZQ', '00abc2', '2619', 'https://a.espncdn.com/i/teamlogos/countries/500/kaz.png', 'Cazaquistão');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('CYP', '195ccd', '445', 'https://a.espncdn.com/i/teamlogos/countries/500/cyp.png', 'Chipre');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('SCO', '1a2d69', '580', 'https://a.espncdn.com/i/teamlogos/countries/500/sco.png', 'Escócia');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('SVK', '0c2fff', '468', 'https://a.espncdn.com/i/teamlogos/countries/500/svk.png', 'Eslováquia');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('SVN', 'ffffff', '472', 'https://a.espncdn.com/i/teamlogos/countries/500/svn.png', 'Eslovênia');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('EST', '195ccd', '444', 'https://a.espncdn.com/i/teamlogos/countries/500/est.png', 'Estonia');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('FIN', '003580', '458', 'https://a.espncdn.com/i/teamlogos/countries/500/fin.png', 'Finlândia');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('GEO', 'ffffff', '584', 'https://a.espncdn.com/i/teamlogos/countries/500/geo.png', 'Georgia');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('GIB', 'DE2918', '16721', 'https://a.espncdn.com/i/teamlogos/soccer/500/16721.png', 'Gibraltar');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('GRE', '295da8', '455', 'https://a.espncdn.com/i/teamlogos/countries/500/gre.png', 'Grécia');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('HUN', 'ce2029', '480', 'https://a.espncdn.com/i/teamlogos/countries/500/hun.png', 'Hungria');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('FRO', 'ffffff', '447', 'https://a.espncdn.com/i/teamlogos/countries/500/fro.png', 'Ilhas Faroe');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('IRL', '049a64', '476', 'https://a.espncdn.com/i/teamlogos/countries/500/irl.png', 'Irlanda');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('NIR', 'cc0000', '586', 'https://a.espncdn.com/i/teamlogos/countries/500/nir.png', 'Irlanda do Norte');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('ISL', '0c2fff', '470', 'https://a.espncdn.com/i/teamlogos/countries/500/isl.png', 'Islândia');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('ISR', '2f4fa2', '461', 'https://a.espncdn.com/i/teamlogos/countries/500/isr.png', 'Israel');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('ITA', '103cd6', '162', 'https://a.espncdn.com/i/teamlogos/countries/500/ita.png', 'Itália');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('KOS', '0000cd', '18272', 'https://a.espncdn.com/i/teamlogos/soccer/500/18272.png', 'Kosovo');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('LTN', '992242', '456', 'https://a.espncdn.com/i/teamlogos/countries/500/lva.png', 'Letônia');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('LIE', '0000cd', '589', 'https://a.espncdn.com/i/teamlogos/countries/500/lie.png', 'Liechtenstein');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('LTU', 'ffe400', '460', 'https://a.espncdn.com/i/teamlogos/countries/500/ltu.png', 'Lituânia');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('LUX', 'E70000', '582', 'https://a.espncdn.com/i/teamlogos/countries/500/lux.png', 'Luxemburgo');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('MDN', 'E70000', '463', 'https://a.espncdn.com/i/teamlogos/countries/500/mkd.png', 'Macedônia do Norte');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('MLT', 'DE2400', '453', 'https://a.espncdn.com/i/teamlogos/countries/500/mlt.png', 'Malta');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('MDA', '0046ae', '483', 'https://a.espncdn.com/i/teamlogos/countries/500/mda.png', 'Moldávia');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('MNE', 'E70000', '6775', 'https://a.espncdn.com/i/teamlogos/countries/500/mtg.png', 'Montenegro');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('NOR', 'ef2b2d', '464', 'https://a.espncdn.com/i/teamlogos/countries/500/nor.png', 'Noruega');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('CZE', 'd7141a', '450', 'https://a.espncdn.com/i/teamlogos/countries/500/cze.png', 'República Tcheca');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('ROM', 'fcd116', '473', 'https://a.espncdn.com/i/teamlogos/countries/500/rom.png', 'Romênia');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('SMR', '00bfff', '588', 'https://a.espncdn.com/i/teamlogos/countries/500/smr.png', 'San Marino');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('SWE', 'fecb00', '466', 'https://a.espncdn.com/i/teamlogos/countries/500/swe.png', 'Suécia');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('TUR', 'ffffff', '465', 'https://a.espncdn.com/i/teamlogos/countries/500/tur.png', 'Turquia');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('UCR', 'fede00', '457', 'https://a.espncdn.com/i/teamlogos/countries/500/ukr.png', 'Ucrânia');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('AUT', 'd72b2c', '474', 'https://a.espncdn.com/i/teamlogos/countries/500/aut.png', 'Áustria');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('BOL', '00843d', '204', 'https://a.espncdn.com/i/teamlogos/countries/500/bol.png', 'Bolívia');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('CHI', 'd3362a', '207', 'https://a.espncdn.com/i/teamlogos/countries/500/chi.png', 'Chile');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('COL', 'fbd632', '208', 'https://a.espncdn.com/i/teamlogos/countries/500/col.png', 'Colômbia');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('JAM', '348b42', '1038', 'https://a.espncdn.com/i/teamlogos/countries/500/jam.png', 'Jamaica');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('PAN', 'd21034', '2659', 'https://a.espncdn.com/i/teamlogos/countries/500/pan.png', 'Panamá');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('PAR', 'ea2300', '210', 'https://a.espncdn.com/i/teamlogos/countries/500/par.png', 'Paraguai');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('Peru', 'cb292e', '211', 'https://a.espncdn.com/i/teamlogos/countries/500/per.png', 'Peru');
insert into "teams" ("abbreviation", "color", "id", "logo", "name") values ('VEN', 'd02a36', '213', 'https://a.espncdn.com/i/teamlogos/countries/500/ven.png', 'Venezuela');
