// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	user "github.com/modasby/futeboxd-backend/core/internal/user"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CheckRecoverToken mocks base method.
func (m *MockRepository) CheckRecoverToken(ctx context.Context, token string) (*user.Recover, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckRecoverToken", ctx, token)
	ret0, _ := ret[0].(*user.Recover)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckRecoverToken indicates an expected call of CheckRecoverToken.
func (mr *MockRepositoryMockRecorder) CheckRecoverToken(ctx, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckRecoverToken", reflect.TypeOf((*MockRepository)(nil).CheckRecoverToken), ctx, token)
}

// Create mocks base method.
func (m *MockRepository) Create(ctx context.Context, user *user.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRepositoryMockRecorder) Create(ctx, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepository)(nil).Create), ctx, user)
}

// Exists mocks base method.
func (m *MockRepository) Exists(ctx context.Context, username, email string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", ctx, username, email)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockRepositoryMockRecorder) Exists(ctx, username, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockRepository)(nil).Exists), ctx, username, email)
}

// FindOneByCredential mocks base method.
func (m *MockRepository) FindOneByCredential(ctx context.Context, credential string) (*user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOneByCredential", ctx, credential)
	ret0, _ := ret[0].(*user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOneByCredential indicates an expected call of FindOneByCredential.
func (mr *MockRepositoryMockRecorder) FindOneByCredential(ctx, credential interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOneByCredential", reflect.TypeOf((*MockRepository)(nil).FindOneByCredential), ctx, credential)
}

// FindOneByIdOrUsername mocks base method.
func (m *MockRepository) FindOneByIdOrUsername(ctx context.Context, username string) (*user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOneByIdOrUsername", ctx, username)
	ret0, _ := ret[0].(*user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOneByIdOrUsername indicates an expected call of FindOneByIdOrUsername.
func (mr *MockRepositoryMockRecorder) FindOneByIdOrUsername(ctx, username interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOneByIdOrUsername", reflect.TypeOf((*MockRepository)(nil).FindOneByIdOrUsername), ctx, username)
}

// SaveRecoverToken mocks base method.
func (m *MockRepository) SaveRecoverToken(ctx context.Context, recover *user.Recover) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveRecoverToken", ctx, recover)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveRecoverToken indicates an expected call of SaveRecoverToken.
func (mr *MockRepositoryMockRecorder) SaveRecoverToken(ctx, recover interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveRecoverToken", reflect.TypeOf((*MockRepository)(nil).SaveRecoverToken), ctx, recover)
}

// Update mocks base method.
func (m *MockRepository) Update(ctx context.Context, user *user.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockRepositoryMockRecorder) Update(ctx, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRepository)(nil).Update), ctx, user)
}
