// Code generated by MockGen. DO NOT EDIT.
// Source: usecase.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	dto "github.com/modasby/futeboxd-backend/core/internal/user/dto"
)

// MockUsecases is a mock of Usecases interface.
type MockUsecases struct {
	ctrl     *gomock.Controller
	recorder *MockUsecasesMockRecorder
}

// MockUsecasesMockRecorder is the mock recorder for MockUsecases.
type MockUsecasesMockRecorder struct {
	mock *MockUsecases
}

// NewMockUsecases creates a new mock instance.
func NewMockUsecases(ctrl *gomock.Controller) *MockUsecases {
	mock := &MockUsecases{ctrl: ctrl}
	mock.recorder = &MockUsecasesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsecases) EXPECT() *MockUsecasesMockRecorder {
	return m.recorder
}

// ChangePassword mocks base method.
func (m *MockUsecases) ChangePassword(ctx context.Context, input *dto.ChangePassword) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangePassword", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// ChangePassword indicates an expected call of ChangePassword.
func (mr *MockUsecasesMockRecorder) ChangePassword(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangePassword", reflect.TypeOf((*MockUsecases)(nil).ChangePassword), ctx, input)
}

// CreateUser mocks base method.
func (m *MockUsecases) CreateUser(ctx context.Context, input *dto.UserInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockUsecasesMockRecorder) CreateUser(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockUsecases)(nil).CreateUser), ctx, input)
}

// EditUser mocks base method.
func (m *MockUsecases) EditUser(ctx context.Context, input *dto.EditUser) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EditUser", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// EditUser indicates an expected call of EditUser.
func (mr *MockUsecasesMockRecorder) EditUser(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EditUser", reflect.TypeOf((*MockUsecases)(nil).EditUser), ctx, input)
}

// GetCurrentUser mocks base method.
func (m *MockUsecases) GetCurrentUser(ctx context.Context) (*dto.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentUser", ctx)
	ret0, _ := ret[0].(*dto.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrentUser indicates an expected call of GetCurrentUser.
func (mr *MockUsecasesMockRecorder) GetCurrentUser(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentUser", reflect.TypeOf((*MockUsecases)(nil).GetCurrentUser), ctx)
}

// RecoverPassword mocks base method.
func (m *MockUsecases) RecoverPassword(ctx context.Context, input *dto.RecoverPassword) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecoverPassword", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecoverPassword indicates an expected call of RecoverPassword.
func (mr *MockUsecasesMockRecorder) RecoverPassword(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecoverPassword", reflect.TypeOf((*MockUsecases)(nil).RecoverPassword), ctx, input)
}

// ResetPassword mocks base method.
func (m *MockUsecases) ResetPassword(ctx context.Context, input *dto.ResetPassword) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetPassword", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResetPassword indicates an expected call of ResetPassword.
func (mr *MockUsecasesMockRecorder) ResetPassword(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetPassword", reflect.TypeOf((*MockUsecases)(nil).ResetPassword), ctx, input)
}
