// Code generated by MockGen. DO NOT EDIT.
// Source: usecase.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	dto "github.com/modasby/futeboxd-backend/core/internal/comment/dto"
	pagination "github.com/modasby/futeboxd-backend/core/pkg/pagination"
)

// MockCommentUsecases is a mock of CommentUsecases interface.
type MockCommentUsecases struct {
	ctrl     *gomock.Controller
	recorder *MockCommentUsecasesMockRecorder
}

// MockCommentUsecasesMockRecorder is the mock recorder for MockCommentUsecases.
type MockCommentUsecasesMockRecorder struct {
	mock *MockCommentUsecases
}

// NewMockCommentUsecases creates a new mock instance.
func NewMockCommentUsecases(ctrl *gomock.Controller) *MockCommentUsecases {
	mock := &MockCommentUsecases{ctrl: ctrl}
	mock.recorder = &MockCommentUsecasesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommentUsecases) EXPECT() *MockCommentUsecasesMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCommentUsecases) Create(ctx context.Context, input *dto.CommentInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockCommentUsecasesMockRecorder) Create(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCommentUsecases)(nil).Create), ctx, input)
}

// Delete mocks base method.
func (m *MockCommentUsecases) Delete(ctx context.Context, commentID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, commentID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCommentUsecasesMockRecorder) Delete(ctx, commentID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCommentUsecases)(nil).Delete), ctx, commentID)
}

// ListByReview mocks base method.
func (m *MockCommentUsecases) ListByReview(ctx context.Context, reviewID int64, page *pagination.Page) ([]dto.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByReview", ctx, reviewID, page)
	ret0, _ := ret[0].([]dto.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByReview indicates an expected call of ListByReview.
func (mr *MockCommentUsecasesMockRecorder) ListByReview(ctx, reviewID, page interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByReview", reflect.TypeOf((*MockCommentUsecases)(nil).ListByReview), ctx, reviewID, page)
}

// ToggleLike mocks base method.
func (m *MockCommentUsecases) ToggleLike(ctx context.Context, commentID int64) (*dto.LikeStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToggleLike", ctx, commentID)
	ret0, _ := ret[0].(*dto.LikeStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ToggleLike indicates an expected call of ToggleLike.
func (mr *MockCommentUsecasesMockRecorder) ToggleLike(ctx, commentID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToggleLike", reflect.TypeOf((*MockCommentUsecases)(nil).ToggleLike), ctx, commentID)
}
