services:
  core-db:
    image: postgres:latest
    env_file: ../services/core/.env
    volumes:
      - ./core/migrations:/docker-entrypoint-initdb.d
    environment:
      - PGPORT=${PGPORT}
    ports:
      - ${PGPORT}:${PGPORT}
    deploy:
      resources:
        limits:
          memory: 1.5g
          cpus: "0.5"
        reservations:
          memory: 1g

  football-db:
    image: postgres:latest
    env_file: ../services/football/.env
    volumes:
      - ./football/migrations:/docker-entrypoint-initdb.d
    ports:
      - ${PGPORT}:${PGPORT}
    deploy:
      resources:
        limits:
          memory: 1.5g
          cpus: "0.5"  # Limita a 50% de um núcleo
        reservations:
          memory: 1g