upstream reviews_service {
    server reviews:8080;
}

upstream football_service {
    server football:8081;
}

server {
    listen 80;

    location /review/ {
        proxy_pass http://reviews_service/review/;
    }

    location /football/ {
        proxy_pass http://football_service/football/;
    }
}