services:
  core-db:
    networks:
      - core_db
    image: postgres:latest
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
    environment:
      - PGPORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=futeboxd-core
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          memory: 1.5g
          cpus: "0.5"
        reservations:
          memory: 1g

networks:
  core_db:
    driver: bridge