services:
  core-db:
    container_name: "futeboxd-core-db"
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - PGPORT=${DB_PORT}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
