// Code generated by MockGen. DO NOT EDIT.
// Source: client.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	football "github.com/modasby/futeboxd-backend/core/pkg/football"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// GetMatch mocks base method.
func (m *MockClient) GetMatch(matchID int64) (*football.Match, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMatch", matchID)
	ret0, _ := ret[0].(*football.Match)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMatch indicates an expected call of GetMatch.
func (mr *MockClientMockRecorder) GetMatch(matchID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMatch", reflect.TypeOf((*MockClient)(nil).GetMatch), matchID)
}

// GetMatches mocks base method.
func (m *MockClient) GetMatches(matchIDs []int64) ([]football.Match, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMatches", matchIDs)
	ret0, _ := ret[0].([]football.Match)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMatches indicates an expected call of GetMatches.
func (mr *MockClientMockRecorder) GetMatches(matchIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMatches", reflect.TypeOf((*MockClient)(nil).GetMatches), matchIDs)
}

// GetMatchesMap mocks base method.
func (m *MockClient) GetMatchesMap(matchIDs []int64) (map[int64]football.Match, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMatchesMap", matchIDs)
	ret0, _ := ret[0].(map[int64]football.Match)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMatchesMap indicates an expected call of GetMatchesMap.
func (mr *MockClientMockRecorder) GetMatchesMap(matchIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMatchesMap", reflect.TypeOf((*MockClient)(nil).GetMatchesMap), matchIDs)
}

// GetTeam mocks base method.
func (m *MockClient) GetTeam(teamID int64) (*football.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTeam", teamID)
	ret0, _ := ret[0].(*football.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTeam indicates an expected call of GetTeam.
func (mr *MockClientMockRecorder) GetTeam(teamID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTeam", reflect.TypeOf((*MockClient)(nil).GetTeam), teamID)
}
