FROM golang:1.23.5 AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o api ./cmd/api/main.go

FROM alpine:latest AS runner

WORKDIR /root/

COPY --from=builder /app/api ./api
COPY --from=builder /app/config/config.yml ./config.yml

CMD ["sh", "-c", "./api"]