# Definir a imagem base com Python 3.12.3
FROM python:3.12.3-slim

# Definir o diretório de trabalho dentro do container
WORKDIR /app

# Copiar o arquivo de dependências para o container
COPY requirements.txt .

# Instalar as dependências do projeto
RUN pip install --no-cache-dir -r requirements.txt

# Copiar todo o código do projeto para dentro do container
COPY src/ .

# Expor a porta que o aplicativo vai rodar
EXPOSE 8000

# Definir o comando para rodar o aplicativo (ajuste conforme necessário)
CMD ["python", "main.py"]
